### ISSUE TITLE
[OPS] Create a basic CI

### ISSUE THREAD

**Issue by ptrouillard** [amauryleclerc/banana#30]
As a developer, I need to build the JAR of the application automatically and to deploy it on a ftp server

URL would be :
ftp://pedrocloud.freeboxos.fr/fr/aleclerc/sprint-graph/2.0.0-SNAPSHOT/

Jenkins use Pipeline script stored within the git repository (build.pipeline)

Sensible information (ftp passwords) should not be stored anywhere within GIT. A settings.xml file will be provided to jenkins maven installation in order to get access to FTP.

FTP would be accessible for humans via basic authentication mechanism.

**Comment by ptrouillard** [comment]
To check : 
* access to FTP repository from outside my home (user/pwd provided in settings.xml sent)
* build/deploy triggered every 5 min after a commit to git : snapshot artifact should be present in FTP afterwards

**Comment by amauryleclerc** [comment]
@ptrouillard Where is the jenkins ?

**Comment by ptrouillard** [comment]
@amauryleclerc The jenkins instance is deployed on a RASPI2 at home

**Comment by amauryleclerc** [comment]
Its works with filezilla in actif mode but i can't do a mvn deploy.

`[DEBUG]   (f) reactorProjects = [MavenProject: fr.aleclerc:sprint-graph:2.0.0-SNAPSHOT @ H:\sprint-graph\sprint-graph-back\pom.xml]
[DEBUG]   (f) retryFailedDeploymentCount = 1
[DEBUG]   (f) skip = false
[DEBUG]   (f) updateReleaseInfo = false
[DEBUG] -- end configuration --
[DEBUG] Using transporter WagonTransporter with priority -1.0 for ftp://pedrocloud.freeboxos.fr/home/minion/
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for ftp://pedrocloud.freeboxos.fr/home/minion/ with username=***, password=***
Downloading: ftp://pedrocloud.freeboxos.fr/home/minion/fr/aleclerc/sprint-graph/2.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata fr.aleclerc:sprint-graph:2.0.0-SNAPSHOT/maven-metadata.xml from/to server1 (ftp://pedrocloud.freeboxos.fr/home/minion/): Error transferring file via FTP
org.eclipse.aether.transfer.MetadataTransferException: Could not transfer metadata fr.aleclerc:sprint-graph:2.0.0-SNAPSHOT/maven-metadata.xml from/to server1 (ftp://pedrocloud.freeboxos.fr/home/minion/): Error transferring file via FTP
        at org.eclipse.aether.connector.basic.MetadataTransportListener.transferFailed(MetadataTransportListener.java:43)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:222)
        at org.eclipse.aether.internal.impl.DefaultDeployer.upload(DefaultDeployer.java:417)
        at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:290)
        at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
        at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:139)
        at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:171)
        at org.apache.maven.plugin.deploy.DeployMojo.deployProject(DeployMojo.java:250)
        at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:169)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file via FTP
        at org.apache.maven.wagon.providers.ftp.FtpWagon.fillInputData(FtpWagon.java:376)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
        ... 33 more
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:762)
        at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:657)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3097)
        at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:3072)
        at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2731)
        at org.apache.maven.wagon.providers.ftp.FtpWagon.fillInputData(FtpWagon.java:353)
        ... 41 more
`

**Comment by amauryleclerc** [comment]
Jenkins works, when i commit, i see the new artifact in the FTP
